FROM maven:3.8.4-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:17-alpine
EXPOSE 80
COPY --from=build /home/app/target/code-with-quarkus-0.0.1-SNAPSHOT.jar app/app.jar
ENTRYPOINT ["java", "-jar","/app/app.jar"]



## Stage 1 : build with maven builder image with native capabilities

FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 AS build
COPY . /tmp/my-project
USER root
RUN chown -R quarkus /tmp/my-project
USER quarkus
RUN mvn -f /tmp/my-project/pom.xml  clean package

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /usr/src/app/target/
COPY --from=build /tmp/my-project/target/*-runner /usr/src/app/target/application
RUN chmod 775 /usr/src/app/target
EXPOSE 8080
CMD ["./application", "-XX:+PrintGC", "-XX:+PrintGCTimeStamps", "-XX:+VerboseGC", "+XX:+PrintHeapShape", "-Xmx128m", "-Dquarkus.http.host=0.0.0.0"]

